# Generated by Django 3.1.2 on 2021-10-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_active_line_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active_line_group',
            new_name='current_line_group_activated',
        ),
    ]
