# Generated by Django 3.1.2 on 2020-10-29 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20201029_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='indicated_by',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Indicado por'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='quality',
            field=models.SmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, verbose_name='Qualidade (1 - 5)'),
        ),
    ]
