# Generated by Django 3.1.2 on 2020-10-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20201029_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, verbose_name='Anotações'),
        ),
    ]
