# Generated by Django 3.1.2 on 2020-10-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='waid',
            field=models.CharField(blank=True, max_length=1024, verbose_name='WhatsApp ID'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tels',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telefone de Contato'),
        ),
    ]
