# Generated by Django 3.1.2 on 2020-10-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201029_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tels',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Telefone'),
        ),
    ]
