# Generated by Django 3.1.2 on 2020-10-29 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_auto_20201029_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='tels',
            new_name='tel',
        ),
    ]
