# Generated by Django 3.1.2 on 2020-10-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20201029_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='indicated_by',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Indicado por'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='tel',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='waid',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='WhatsApp ID'),
        ),
    ]
