# Generated by Django 3.1.2 on 2020-10-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_auto_20201029_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
