# Generated by Django 3.1.2 on 2020-10-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('sem_interesse', 'Contato Realizado [Sem Interesse]'), ('contato_invalido', 'Contato inválido'), ('ignorando', 'Está rejeitando os contatos'), ('agendamento', 'Agendamento'), ('ganho', 'Apresentação Realizada [Ganho]'), ('perdido', 'Apresentação Realizada [Perdido]')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
