# Generated by Django 3.1.2 on 2020-10-31 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_auto_20201031_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='next_contact',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Próximo contato'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('sem_interesse', 'Contato realizado [SEM INTERESSE]'), ('contato_invalido', 'Contato inválido'), ('ignorando', 'Está rejeitando os contatos'), ('agendamento', 'Agendamento'), ('ganho', 'Apresentação realizada [GANHO]'), ('perdido', 'Apresentação realizada [PERDIDO]')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
