# Generated by Django 3.1.2 on 2020-10-31 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20201031_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('sem_interesse', 'Contato realizado [ SEM INTERESSE ]'), ('contato_invalido', 'Contato inválido'), ('ignorando', 'Está rejeitando os contatos'), ('agendamento', 'Agendamento'), ('acompanhamento', 'Acompanhamento'), ('ganho', 'Apresentação realizada [ GANHO ]'), ('perdido', 'Apresentação realizada [ PERDIDO ]')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
