# Generated by Django 3.1.2 on 2020-11-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_auto_20201031_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'NOVO'), ('tentando_contato', 'Tentando Contato'), ('processando', 'PROCESSANDO'), ('sem_interesse', 'SEM INTERESSE'), ('contato_invalido', 'CONTATO INVÁLIDO'), ('ignorando', 'REJEITANDO AS LIGAÇÕES'), ('agendamento', 'AGENDAMENTO'), ('acompanhamento', 'ACOMPANHAMENTO'), ('ganho', 'GANHO'), ('perdido', 'PERDIDO')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
