# Generated by Django 3.1.2 on 2020-11-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20201102_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='indicated_by_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Indicação'),
        ),
    ]
