# Generated by Django 3.1.2 on 2020-11-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_lead_indicated_by_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='indicated_by_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e hora da indicação'),
        ),
    ]
