# Generated by Django 3.1.2 on 2020-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20201106_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Anotações'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'NOVO'), ('tentando_contato', 'TENTANDO CONTATO'), ('processando', 'PROCESSANDO'), ('sem_interesse', 'SEM INTERESSE'), ('sem_condicoes_financeiras', 'SEM CONDIÇÕES FINANCEIRAS'), ('contato_invalido', 'CONTATO INVÁLIDO'), ('ignorando', 'REJEITANDO AS LIGAÇÕES'), ('agendamento', 'AGENDAMENTO'), ('acompanhamento', 'ACOMPANHAMENTO'), ('ganho', 'GANHO'), ('perdido', 'PERDIDO')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
