# Generated by Django 3.1.2 on 2020-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_auto_20201208_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Localização: País/Cidade'),
        ),
    ]
