# Generated by Django 3.1.2 on 2020-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_auto_20201209_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='gmt',
            field=models.IntegerField(choices=[(None, 'Selecionar'), (-1, 'GMT-1'), (-2, 'GMT-2'), (-3, 'GMT-3'), (-4, 'GMT-4'), (-5, 'GMT-5'), (-6, 'GMT-6'), (-7, 'GMT-7'), (-8, 'GMT-8'), (-9, 'GMT-9'), (-10, 'GMT-10'), (-11, 'GMT-11'), (-12, 'GMT-12'), (0, 'GMT'), (1, 'GMT+1'), (2, 'GMT+2'), (3, 'GMT+3'), (4, 'GMT+4'), (5, 'GMT+5'), (6, 'GMT+6'), (7, 'GMT+7'), (8, 'GMT+8'), (9, 'GMT+9'), (10, 'GMT+10'), (11, 'GMT+11'), (12, 'GMT+12')], default=-3, verbose_name='GMT'),
        ),
    ]
