# Generated by Django 3.1.2 on 2020-12-13 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0024_auto_20201213_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads_lead', to='leads.lead', verbose_name='Lead/Referenciador'),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='gmt',
            field=models.IntegerField(blank=True, default=-3, null=True, verbose_name='GMT'),
        ),
        migrations.AlterField(
            model_name='referrer',
            name='name',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Nome do Referenciador'),
        ),
    ]
