# Generated by Django 3.1.2 on 2020-12-14 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_auto_20201213_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='leads',
            field=models.ManyToManyField(related_name='leads', to='leads.Lead'),
        ),
    ]
