# Generated by Django 3.1.2 on 2020-12-15 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_referrer_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='short_description',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Descrição curta da "linha"'),
        ),
    ]
