# Generated by Django 3.1.2 on 2021-01-05 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_lead_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('tentando_contato', 'Tentando Contato'), ('sem_interesse', 'Sem Interesse'), ('sem_condicoes_financeiras', 'Sem Dinheiro'), ('contato_invalido', 'Contato Inválido'), ('agendamento', 'Agendamento'), ('ganho', 'Ganho'), ('perdido', 'Perdido')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
