# Generated by Django 3.1.2 on 2021-01-07 04:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_auto_20210105_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(max_length=150, verbose_name='Descrição do template')),
                ('content', models.CharField(max_length=1024, verbose_name='Conteúdo do template')),
            ],
            options={
                'verbose_name': 'Modelo de Mensagem para WhatsApp',
                'verbose_name_plural': 'Modelos de Mensagens para WhatsApp',
            },
        ),
    ]
