# Generated by Django 3.1.2 on 2021-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_auto_20210107_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('tentando_contato', 'Tentando'), ('agendamento', 'Agendamento'), ('acompanhamento', 'Acompanhamento'), ('perdido', 'Perdido'), ('ganho', 'Ganho')], default='novo', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status_lost_justification',
            field=models.CharField(blank=True, choices=[('', 'Selecionar'), ('sem_interesse', 'Sem Interesse'), ('sem_dinheiro', 'Sem Dinheiro'), ('ja_estuda_ingles', 'Já Estuda Inglês'), ('ja_fala_ingles', 'Já Fala Inglês'), ('invalido', 'Inválido'), ('duplicado', 'Duplicado'), ('ignorando', 'Ignorando'), ('bloqueado', 'Bloqueado'), ('desligou_na_cara', 'Desligou na Cara'), ('rejeitando', 'Rejeitando'), ('outro', 'Outro')], max_length=300, null=True, verbose_name='Justificativa da Perda'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
