# Generated by Django 3.1.2 on 2021-01-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_auto_20210108_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapptemplate',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='Ordem'),
        ),
    ]
