# Generated by Django 3.1.2 on 2021-01-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0036_auto_20210109_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referrer',
            options={'verbose_name': 'Referenciador', 'verbose_name_plural': 'Referenciadores'},
        ),
        migrations.AlterModelOptions(
            name='whatsapptemplate',
            options={'ordering': ['order'], 'verbose_name': 'Modelo de Mensagem para WhatsApp', 'verbose_name_plural': 'Modelos de Mensagens para WhatsApp'},
        ),
        migrations.AddField(
            model_name='lead',
            name='qualified',
            field=models.BooleanField(default=False, verbose_name='Qualificado?'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status_lost_justification',
            field=models.CharField(blank=True, choices=[('', 'Selecionar'), ('sem_interesse', 'Sem Interesse'), ('nao_e_prioridade', 'Não é prioridade'), ('sem_dinheiro', 'Sem Dinheiro'), ('ja_estuda_ingles', 'Já Estuda Inglês'), ('ja_fala_ingles', 'Já Fala Inglês'), ('invalido', 'Inválido'), ('duplicado', 'Duplicado'), ('ignorando', 'Ignorando'), ('bloqueado', 'Bloqueado'), ('desligou_na_cara', 'Desligou na Cara'), ('rejeitando', 'Rejeitando'), ('outro', 'Outro')], max_length=300, null=True, verbose_name='Justificativa da Perda'),
        ),
    ]
