# Generated by Django 3.1.2 on 2021-01-21 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0037_auto_20210113_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status_lost_justification',
            field=models.CharField(blank=True, choices=[('', 'Selecionar'), ('sem_interesse', 'Sem Interesse'), ('nao_e_prioridade', 'Não é prioridade'), ('sem_dinheiro', 'Sem Dinheiro'), ('ja_estuda_ingles', 'Já Estuda Inglês'), ('ja_fala_ingles', 'Já Fala Inglês'), ('nao_gosta_de_ead', 'Não Gosta de EAD'), ('invalido', 'Inválido'), ('duplicado', 'Duplicado'), ('ignorando', 'Ignorando'), ('bloqueado', 'Bloqueado'), ('desligou_na_cara', 'Desligou na Cara'), ('rejeitando', 'Rejeitando'), ('outro', 'Outro')], max_length=300, null=True, verbose_name='Justificativa da Perda'),
        ),
    ]
