# Generated by Django 3.1.2 on 2021-02-10 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0039_qualified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualified',
            options={'verbose_name': 'Qualificado', 'verbose_name_plural': 'Qualificados'},
        ),
        migrations.AddField(
            model_name='qualified',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Processado?'),
        ),
    ]
