# Generated by Django 3.1.2 on 2021-02-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0040_auto_20210209_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualified',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome'),
        ),
    ]
