# Generated by Django 3.1.2 on 2021-02-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0041_qualified_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualified',
            options={'ordering': ('-created_at',), 'verbose_name': 'Qualificado', 'verbose_name_plural': 'Qualificados'},
        ),
    ]
