# Generated by Django 3.1.2 on 2021-02-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0046_auto_20210220_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo - T1'), ('tentando_contato', 'Tentando - T2'), ('tentando_contato_2', 'Ultimato - T3'), ('agendamento', 'Agendamento'), ('acompanhamento', 'Follow-up'), ('geladeira', 'Geladeira'), ('perdido', 'Perdido'), ('ganho', 'Ganho')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
