# Generated by Django 3.1.2 on 2021-05-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0050_auto_20210422_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo - T1'), ('tentando_contato', 'Tentando - T2'), ('tentando_contato_2', 'Ultimato - T3'), ('geladeira', 'Geladeira'), ('agendamento', 'Agendamento'), ('ghosting', 'Bolo 1'), ('ghosting_2', 'Bolo 2'), ('perdido', 'Perdido'), ('ganho', 'Ganho'), ('invalid', 'Inválido'), ('ultimatum', 'Ultimato')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
