# Generated by Django 3.1.2 on 2021-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0051_auto_20210520_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Ordem'),
        ),
    ]
