# Generated by Django 3.1.2 on 2021-07-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0052_lead_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo [T1]'), ('tentando_contato', 'Tentando [T2]'), ('tentando_contato_2', 'Tentando [T3]'), ('geladeira', 'Geladeira'), ('agendamento', 'Agendamento'), ('agendamento_direct', 'Agendamento Direto'), ('ghosting', 'Bolo 1'), ('ghosting_2', 'Bolo 2'), ('off_2', 'Off 2'), ('invalid', 'Inválido'), ('ultimatum', 'Ultimato'), ('perdido', 'Perdido'), ('off', 'Off'), ('ganho', 'Ganho')], default='novo', max_length=50, verbose_name='Status'),
        ),
    ]
