# Generated by Django 3.1.2 on 2021-09-10 03:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0055_lead_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappTemplateCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria dos Modelos de Mensagens para WhatsApp',
                'verbose_name_plural': 'Categoria dos Modelos de Mensagens para WhatsApp',
            },
        ),
    ]
