# Generated by Django 3.1.2 on 2021-10-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0057_auto_20210910_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='validation',
            field=models.CharField(blank=True, choices=[(None, 'Selecionar'), ('De 5 em 5', '5 em 5'), ('Lista de Transmissão', 'Lista de Transmissão'), ('Não Validada', 'Não Validada'), ('Validada Parcialmente', 'Validada Parcialmente')], max_length=200, null=True, verbose_name='Validação'),
        ),
    ]
