# Generated by Django 3.1.2 on 2021-10-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0058_referrer_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='validation',
            field=models.CharField(blank=True, choices=[(None, 'Selecionar'), ('De 5 em 5', '5 em 5'), ('Lista de Transmissão', 'Lista de Transmissão'), ('Não Validada', 'Não Validada'), ('Não Validada (Lead Mentiu)', 'Não Validada (Lead Mentiu)'), ('Validada Parcialmente', 'Validada Parcialmente'), ('Outro', 'Outro')], max_length=200, null=True, verbose_name='Validação'),
        ),
    ]
