# Generated by Django 3.1.2 on 2021-10-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0060_lead_best_time_to_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='best_time_to_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Melhor horário para contato'),
        ),
    ]
