# Generated by Django 3.1.2 on 2021-10-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0062_referrercategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrercategory',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nome da Categoria'),
        ),
    ]
