# Generated by Django 3.1.2 on 2021-10-21 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0065_auto_20211021_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrer',
            name='line_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.linegrupo', verbose_name='Categoria da Linha'),
        ),
    ]
