# Generated by Django 3.1.2 on 2021-10-21 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('leads', '0066_referrer_line_grupo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineGrupo',
            new_name='LineGroup',
        ),
        migrations.RenameField(
            model_name='referrer',
            old_name='line_grupo',
            new_name='line_group',
        ),
    ]
