# Generated by Django 3.1.2 on 2021-10-22 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0067_auto_20211021_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrer',
            name='line_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.linegroup', verbose_name='Grupo da Linha'),
        ),
    ]
