# Generated by Django 3.1.2 on 2020-11-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_delete_activity'),
        ('activities', '0003_activity_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Associada ao Lead'),
        ),
    ]
