# Generated by Django 3.1.2 on 2020-12-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20201110_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('call', 'Ligação'), ('whatsapp_message', 'WhatsApp Mensagem'), ('whatsapp_audio', 'WhatsApp Áudio'), ('presentation', 'Apresentação')], default='call', max_length=120, verbose_name='Tipo'),
        ),
    ]
