# Generated by Django 3.1.2 on 2021-04-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20201213_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Notificação Enviada'),
        ),
    ]
