# Generated by Django 3.1.2 on 2021-04-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0007_auto_20210420_1129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Atividade', 'verbose_name_plural': 'Atividades'},
        ),
    ]
