# Generated by Django 3.1.2 on 2021-08-13 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('activities', '0008_auto_20210420_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Dono'),
        ),
    ]
