# Generated by Django 3.1.2 on 2021-08-05 18:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0053_auto_20210716_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('summary', models.CharField(max_length=250, verbose_name='Resumo do Evento')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Início Data e Hora')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fim Data e Hora')),
                ('done', models.BooleanField(default=False, verbose_name='Realizado?')),
                ('google_calendar_calendar_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Calendar: [calendarId]')),
                ('google_calendar_event_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Google Calendar: [eventId]')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Associada ao Lead')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-created_at'],
            },
        ),
    ]
