# Generated by Django 3.1.2 on 2021-09-07 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20210813_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_datetime'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
    ]
