# Generated by Django 3.1.2 on 2021-04-16 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('description', models.CharField(blank=True, max_length=120, null=True, verbose_name='Descrição')),
                ('o_auth_2_json', models.TextField(blank=True, null=True, verbose_name='O Auth 2.0 JSON [ Client Secret ]')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
