# Generated by Django 3.1.2 on 2021-04-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_auto_20210416_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapi',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificador'),
        ),
    ]
