# Generated by Django 3.1.2 on 2021-04-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_googleapi_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapi',
            name='identifier',
            field=models.CharField(max_length=50, unique=True, verbose_name='Identificador'),
        ),
    ]
