# Generated by Django 3.1.2 on 2021-08-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20210805_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_client_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ client_id ]'),
        ),
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_client_secret',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ client_secret ]'),
        ),
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ refresh_token ]'),
        ),
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_scopes',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ scopes ]'),
        ),
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ token ]'),
        ),
        migrations.AlterField(
            model_name='googleapi',
            name='o_auth_2_credentials_token_uri',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Credentials [ token_uri ]'),
        ),
    ]
