# Generated by Django 3.1.2 on 2021-08-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0008_auto_20210805_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleapi',
            name='o_auth_2_token_json',
        ),
        migrations.AddField(
            model_name='googleapi',
            name='calendar_id',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Calendar ID'),
        ),
    ]
