# Generated by Django 3.1.2 on 2021-08-18 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('integrations', '0010_auto_20210805_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='googleapi',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account', verbose_name='Perfil'),
        ),
    ]
