# Generated by Django 3.1.2 on 2021-05-20 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioSpeech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Ordem')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nome')),
                ('audio_file', models.FileField(blank=True, upload_to='academy/audio-speech/', verbose_name='Arquivo do Áudio do Speech')),
            ],
            options={
                'verbose_name': 'Áudio de Entrevista',
                'verbose_name_plural': 'Áudios de Entrevistas',
                'ordering': ('-order',),
            },
        ),
    ]
