# Generated by Django 3.1.2 on 2021-05-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiospeech',
            name='audio_file',
            field=models.FileField(null=True, upload_to='academy/audio-speech/', verbose_name='Arquivo do Áudio do Speech'),
        ),
        migrations.AlterField(
            model_name='audiospeech',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='audiospeech',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Ordem'),
        ),
    ]
