# Generated by Django 3.1.2 on 2021-09-07 04:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_auto_20210520_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Título')),
                ('url', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ('-order',),
            },
        ),
    ]
