# Generated by Django 3.1.2 on 2021-09-07 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_module_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ('order',), 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
    ]
