# Generated by Django 3.1.2 on 2021-09-07 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20210907_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submodule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('title', models.CharField(max_length=500, null=True, verbose_name='Título')),
                ('url', models.SlugField(null=True, unique=True, verbose_name='URL')),
                ('order', models.PositiveSmallIntegerField(default=1, null=True, verbose_name='Ordem')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academy.module', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Submódulo',
                'verbose_name_plural': 'Submódulo',
                'ordering': ('order',),
            },
        ),
    ]
