# Generated by Django 3.1.2 on 2021-07-16 22:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0053_auto_20210716_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('type', models.CharField(choices=[('sem_interesse', 'Sem Interesse'), ('agendamento', 'Agendamento'), ('di', 'DI'), ('lost', 'Entrevista Perdida'), ('win', 'Entrevista Ganha'), ('lost', 'Entrevista Off')], max_length=120, verbose_name='Tipo de Conversa')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.lead', verbose_name='Associada ao Lead')),
            ],
            options={
                'verbose_name': 'Conversa',
                'verbose_name_plural': 'Conversas',
                'ordering': ['-created_at'],
            },
        ),
    ]
